global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "demo"
    static_configs:
      - targets: ["demo:8080"]
    metrics_path: "/api/v1/metrics"
  - job_name: postgres
    static_configs:
      - targets: ["postgres_exporter:9187" ]
